name: dynaMark
version: ${project.version}
main: org.dynamicmarketplace.dynamicmarketplace.DynamicMarketplace
api-version: 1.13
depend: [Vault]
commands:
  buy:
    description: buy an item from the shop
    usage: /buy <item> <amount>
  buyhand:
    description: buy more of the item in your hand
    usage: /buyhand <item> <amount>
  sell:
    description: sell and item to the shop
    usage: /sell <item> <amount>
  sellhand:
    description: sells the item(s) currently in your hand
    usage: /sellhand
  sellall:
    description: sells everything in your inventory
    usage: /sellAll
  cost:
    description: see the cost of buying an item
    usage: /cost <item> <amount>
  iteminfo:
    description: see market info on a specific item
    usage: /itemInfo <item>
  infohand:
    description: see market information for held item
    usage: /infoHand